version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db

  api:
    build:
      context: ./
      dockerfile: ./src/backend/Dockerfile
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo

  front:
    build:
      context: ./
      dockerfile: ./src/frontend/Dockerfile
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3001:3001"
    links:
      - api
    depends_on:
      - api